### ISSUE TITLE
Share & Invite functions along side with the fbapp config json file

### ISSUE THREAD

**Issue by Zelaloui** [Mohammedcha/Facebook-instan-games-SDK#1]
Would you like to add, the ''add to home screen'' button, which (should be called only by detecting an android device).
would you like also, by refering to the facebook documentation, to add the share and invite functions ( Leaderboards maybe ) to the configurable json file,

cheers

**Comment by Mohammedcha** [comment]
https://developers.facebook.com/docs/games/instant-games/sdk/bundle-config
